[package]
name = "common_media"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk = { version = "0.10.3", package = "gtk4", features = ["v4_6"] }
thiserror = {workspace = true}
gstreamer = "0.24.4"
